#########################################################
# Specify the name of the target executable

TARGETS:=s158

#########################################################
# Include common Makefile

include ../makefile_common.mk
